server:
  port: 8880
spring:
  application:
    name: bootcamp-server
  cloud:
    gateway:
      routes:
      - id: micro1
        uri: 'http://localhost:8881'
        predicates:
        - Path=/micro1/**
      - id: micro2
        uri: 'http://localhost:8882'
        predicates:
        - Path=/micro2/**
      - id: micro3
        uri: 'http://localhost:8883'
        predicates:
        - Path=/micro3/**
